# -*- coding: utf-8 -*-
"""join_and_build_views_pdf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvMujRzJH9gp8WIPf2_h840MhmByT4Kg
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
join_and_build_views_pdf.py (robust)
- Chuẩn hoá tên cột theo PDF + chấp nhận các biến thể thường gặp (Shipment_Sh_ID vs Shipment_SH_ID, E_ID vs Emp_ID, …)
- Join thành FACT + build KPI views
- Ghi ra ./outputs/*.csv
"""

import argparse
import sys
from pathlib import Path
import pandas as pd

# ---------- utils ----------
def to_date(x):
    if pd.isna(x) or x == "": return pd.NaT
    return pd.to_datetime(x, errors="coerce")

def must_read(path: Path, label: str) -> pd.DataFrame:
    if not path.exists():
        sys.exit(f"[ERROR] Missing file: {path}  (for {label})")
    try:
        return pd.read_csv(path)
    except Exception as e:
        sys.exit(f"[ERROR] Failed to read {path}: {e}")

def ensure_dir(p: Path):
    p.mkdir(parents=True, exist_ok=True)

def any_rename(df: pd.DataFrame, mapping: dict):
    """
    mapping = {"target_col": ["candidate1","candidate2",...]}
    -> nếu df có candidate nào thì rename nó thành target_col
    """
    ren = {}
    for target, cands in mapping.items():
        for c in cands:
            if c in df.columns:
                ren[c] = target
                break
    if ren:
        df.rename(columns=ren, inplace=True)
    return df

def require_cols(df: pd.DataFrame, cols: list, df_name: str):
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise KeyError(f"[ERROR] {df_name} thiếu cột {missing}. Columns hiện có: {list(df.columns)}")

# ---------- core ----------
def build(data_dir: Path, out_dir: Path):
    print(f"[INFO] Reading CSVs from: {data_dir.resolve()}")

    # read
    emp  = must_read(data_dir / "Employee_Details.csv", "Employee_Details")
    mem  = must_read(data_dir / "Membership.csv", "Membership")
    cust = must_read(data_dir / "Customer.csv", "Customer")
    pay  = must_read(data_dir / "Payment_Details.csv", "Payment_Details")
    ship = must_read(data_dir / "Shipment_Details.csv", "Shipment_Details")
    stt  = must_read(data_dir / "Status.csv", "Status")
    mapx = must_read(data_dir / "employee_manages_shipment.csv", "employee_manages_shipment")

    # --- normalize column names (accept both PDF & Kaggle variants)

    # Employee: Emp_* (PDF) hoặc E_* (Kaggle)
    any_rename(emp, {
        "Employee_ID":           ["Emp_ID","E_ID"],
        "Employee_Name":         ["Emp_NAME","E_NAME"],
        "Employee_Branch":       ["Emp_BRANCH","E_BRANCH"],
        "Employee_Designation":  ["Emp_DESIGNATION","E_DESIGNATION"],
        "Employee_Address":      ["Emp_ADDR","E_ADDR"],
        "Employee_Contact":      ["Emp_CONT_NO","E_CONT_NO"],
    })

    # Membership
    any_rename(mem, {
        "M_ID":       ["M_ID"],
        "Start_date": ["START_DATE","Start_date"],
        "End_date":   ["END_DATE","End_date"],
    })
    for c in ("Start_date","End_date"):
        if c in mem.columns: mem[c] = mem[c].apply(to_date)

    # Customer
    any_rename(cust, {
        "C_ID":        ["Cust_ID","C_ID"],
        "C_NAME":      ["Cust_NAME","C_NAME"],
        "C_EMAIL_ID":  ["Cust_EMAIL_ID","C_EMAIL_ID"],
        "C_CONT_NO":   ["Cust_CONT_NO","C_CONT_NO"],
        "C_ADDR":      ["Cust_ADDR","C_ADDR"],
        "C_TYPE":      ["Cust_TYPE","C_TYPE"],
        "M_ID":        ["Membership_M_ID","M_ID"],
    })

    # Payment
    any_rename(pay, {
        "Payment_ID":     ["PAYMENT_ID","Payment_ID"],
        "Amount":         ["AMOUNT","Amount"],
        "Payment_Status": ["PAYMENT_STATUS","Payment_Status"],
        "Payment_Date":   ["PAYMENT_DATE","Payment_Date","P_DATE"],
        "Payment_Method": ["PAYMENT_MODE","Payment_Method","P_MODE"],
        "SH_ID":          ["Shipment_SH_ID","Shipment_Sh_ID","SH_ID"],
        "C_ID":           ["Shipment_Client_C_ID","C_ID"],
    })
    if "Payment_Date" in pay.columns: pay["Payment_Date"] = pay["Payment_Date"].apply(to_date)

    # Shipment
    any_rename(ship, {
        "SH_ID":       ["SD_ID","SH_ID"],
        "SH_CONTENT":  ["SD_CONTENT","SH_CONTENT"],
        "SH_DOMAIN":   ["SD_DOMAIN","SH_DOMAIN"],
        "SER_TYPE":    ["SD_TYPE","SER_TYPE"],
        "SH_WEIGHT":   ["SD_WEIGHT","SH_WEIGHT"],
        "SH_CHARGES":  ["SD_CHARGES","SH_CHARGES","SD-CHARGES"],
        "SR_ADDR":     ["SD_ADDR","SR_ADDR"],
        "DS_ADDR":     ["DS_ADDR"],
        "C_ID":        ["Customer_Cust_ID","C_ID"],
    })

    # Status
    any_rename(stt, {
        "Status":        ["CURRENT_ST","Current_Status","Status"],
        "Sent_Date":     ["SENT_DATE","Sent_date","Sent_Date"],
        "Delivery_Date": ["DELIVERY_DATE","Delivery_date","Delivery_Date"],
        "SH_ID":         ["SH_ID"],
    })
    for c in ("Sent_Date","Delivery_Date"):
        if c in stt.columns: stt[c] = stt[c].apply(to_date)

    # Mapping Employee ↔ Shipment
    any_rename(mapx, {
        "SH_ID":          ["Shipment_SH_ID","Shipment_Sh_ID","SH_ID"],
        "Employee_E_ID":  ["Employee_E_ID"],
        # "Status_SH_ID": ["Status_SH_ID"]  # không cần để join
    })

    # sanity keys
    require_cols(ship, ["SH_ID","C_ID"], "Shipment_Details")
    require_cols(mapx, ["SH_ID"], "employee_manages_shipment")

    # --- JOINs (center: Shipment SH_ID)
    fact = ship.merge(mapx, on="SH_ID", how="left") \
               .merge(emp, left_on="Employee_E_ID", right_on="Employee_ID", how="left") \
               .merge(cust, on="C_ID", how="left") \
               .merge(mem,  on="M_ID", how="left") \
               .merge(stt,  on="SH_ID", how="left") \
               .merge(pay,  on=["SH_ID","C_ID"], how="left")

    # Derived
    if "Sent_Date" in fact.columns and "Delivery_Date" in fact.columns:
        fact["delivery_days"] = (fact["Delivery_Date"] - fact["Sent_Date"]).dt.days
    else:
        fact["delivery_days"] = pd.NA

    fact["Status_norm"] = fact.get("Status", pd.Series(dtype=str)).astype(str).str.upper()
    fact["is_delivered"] = fact["Status_norm"].isin(["DELIVERED","DELIVERED ✅","DELIVERED✔️"])
    fact["is_cancelled"] = fact["Status_norm"].isin(["NOT DELIVERED","CANCELLED","RETURNED"])
    fact["is_ontime"]   = fact["is_delivered"] & fact["delivery_days"].notna() & (fact["delivery_days"] <= 7)

    # Select tidy columns
    keep = [
        "SH_ID","C_ID","C_NAME","C_EMAIL_ID","C_CONT_NO","C_ADDR","C_TYPE",
        "M_ID","Start_date","End_date",
        "Employee_ID","Employee_Name","Employee_Designation","Employee_Branch","Employee_Address","Employee_Contact",
        "SH_CONTENT","SH_DOMAIN","SER_TYPE","SH_WEIGHT","SH_CHARGES","SR_ADDR","DS_ADDR",
        "Status","Sent_Date","Delivery_Date","delivery_days","is_delivered","is_cancelled","is_ontime",
        "Payment_ID","Payment_Method","Payment_Status","Payment_Date","Amount"
    ]
    fact = fact[[c for c in keep if c in fact.columns]].copy()

    # KPI helpers
    def exist(c): return c in fact.columns
    def safe_mean(s): return round(s.mean(skipna=True), 4) if len(s) else None
    def safe_sum(s):  return float(s.sum(skipna=True)) if len(s) else 0.0

    overview = pd.DataFrame([{
        "total_orders": len(fact.drop_duplicates(subset=["SH_ID"])) if exist("SH_ID") else len(fact),
        "delivered_orders": int(fact["is_delivered"].sum()) if exist("is_delivered") else 0,
        "cancelled_orders": int(fact["is_cancelled"].sum()) if exist("is_cancelled") else 0,
        "ontime_rate": safe_mean(fact["is_ontime"]) if exist("is_ontime") else None,
        "avg_delivery_days": round(fact["delivery_days"].mean(skipna=True), 2) if exist("delivery_days") else None,
        "total_revenue": safe_sum(fact["Amount"]) if exist("Amount") else 0.0
    }])

    if exist("SR_ADDR"):
        kpi_by_region = (fact.groupby("SR_ADDR", dropna=False)
                         .agg(total_orders=("SH_ID","count"),
                              ontime_rate=("is_ontime","mean") if exist("is_ontime") else ("SH_ID","size"),
                              cancel_rate=("is_cancelled","mean") if exist("is_cancelled") else ("SH_ID","size"),
                              avg_delivery_days=("delivery_days","mean") if exist("delivery_days") else ("SH_ID","size"),
                              revenue=("Amount","sum") if exist("Amount") else ("SH_ID","size"))
                         .reset_index().rename(columns={"SR_ADDR":"Origin"}))
    else:
        kpi_by_region = pd.DataFrame(columns=["Origin","total_orders","ontime_rate","cancel_rate","avg_delivery_days","revenue"])

    if exist("Employee_Name"):
        kpi_by_employee = (fact.groupby("Employee_Name", dropna=False)
                           .agg(total_orders=("SH_ID","count"),
                                ontime_rate=("is_ontime","mean") if exist("is_ontime") else ("SH_ID","size"),
                                avg_delivery_days=("delivery_days","mean") if exist("delivery_days") else ("SH_ID","size"),
                                revenue=("Amount","sum") if exist("Amount") else ("SH_ID","size"))
                           .reset_index())
    else:
        kpi_by_employee = pd.DataFrame(columns=["Employee_Name","total_orders","ontime_rate","avg_delivery_days","revenue"])

    if exist("M_ID"):
        kpi_by_membership = (fact.groupby("M_ID", dropna=False)
                             .agg(total_orders=("SH_ID","count"),
                                  ontime_rate=("is_ontime","mean") if exist("is_ontime") else ("SH_ID","size"),
                                  avg_delivery_days=("delivery_days","mean") if exist("delivery_days") else ("SH_ID","size"),
                                  revenue=("Amount","sum") if exist("Amount") else ("SH_ID","size"))
                             .reset_index())
    else:
        kpi_by_membership = pd.DataFrame(columns=["M_ID","total_orders","ontime_rate","avg_delivery_days","revenue"])

    if exist("Payment_Method"):
        kpi_by_payment = (fact.groupby("Payment_Method", dropna=False)
                          .agg(payment_count=("SH_ID","count"),
                               total_amount=("Amount","sum") if exist("Amount") else ("SH_ID","size"))
                          .reset_index())
    else:
        kpi_by_payment = pd.DataFrame(columns=["Payment_Method","payment_count","total_amount"])

    if exist("Sent_Date") and exist("Status"):
        kpi_daily_status = (fact.assign(Date=fact["Sent_Date"].dt.date)
                            .groupby(["Date","Status"], dropna=False)
                            .agg(orders=("SH_ID","count")).reset_index())
    else:
        kpi_daily_status = pd.DataFrame(columns=["Date","Status","orders"])

    # write
    ensure_dir(out_dir)
    fact.to_csv(out_dir / "fact_shipments.csv", index=False, encoding="utf-8")
    overview.to_csv(out_dir / "kpi_overview.csv", index=False, encoding="utf-8")
    kpi_by_region.to_csv(out_dir / "kpi_by_region.csv", index=False, encoding="utf-8")
    kpi_by_employee.to_csv(out_dir / "kpi_by_employee.csv", index=False, encoding="utf-8")
    kpi_by_membership.to_csv(out_dir / "kpi_by_membership.csv", index=False, encoding="utf-8")
    kpi_by_payment.to_csv(out_dir / "kpi_by_payment.csv", index=False, encoding="utf-8")
    kpi_daily_status.to_csv(out_dir / "kpi_daily_status.csv", index=False, encoding="utf-8")
    print(f"[OK] wrote outputs to: {out_dir.resolve()}")

# ---------- CLI ----------
def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data_dir", type=Path, default=Path("./data"))
    ap.add_argument("--out_dir", type=Path, default=Path("./outputs"))
    return ap.parse_args()

if __name__ == "__main__":
    args = parse_args()
    build(args.data_dir, args.out_dir)