# -*- coding: utf-8 -*-
"""push_to_sheet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvMujRzJH9gp8WIPf2_h840MhmByT4Kg
"""

#!/usr/bin/env python3
"""
push_to_sheet.py
- Đọc các CSV đã build trong ./outputs
- Tạo/cập nhật các tab tương ứng trong Google Sheet
- Yêu cầu:
    - .env có GOOGLE_SHEET_KEY=<your_sheet_key>
    - service_account.json đặt ở thư mục gốc (KHÔNG commit lên Git)
    - Đã share Google Sheet cho email service account (quyền Editor)
Cách chạy:
    python scripts/push_to_sheet.py --out_dir outputs
"""

import os
import argparse
from pathlib import Path
import pandas as pd
from dotenv import load_dotenv
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# ------------ Config ------------
TAB_MAP = {
    "fact_shipments.csv":   "fact_shipments",
    "kpi_overview.csv":     "kpi_overview",
    "kpi_by_region.csv":    "kpi_by_region",
    "kpi_by_employee.csv":  "kpi_by_employee",
    "kpi_by_membership.csv":"kpi_by_membership",
    "kpi_by_payment.csv":   "kpi_by_payment",
    "kpi_daily_status.csv": "kpi_daily_status",
}

def load_env():
    # tìm .env ở thư mục hiện tại
    load_dotenv(dotenv_path=Path(".")/".env")
    sheet_key = os.getenv("GOOGLE_SHEET_KEY")
    if not sheet_key:
        raise RuntimeError("GOOGLE_SHEET_KEY not found. Add it to your .env")
    return sheet_key

def auth_gspread():
    scope = [
        "https://spreadsheets.google.com/feeds",
        "https://www.googleapis.com/auth/drive",
    ]
    creds = ServiceAccountCredentials.from_json_keyfile_name("service_account.json", scope)
    return gspread.authorize(creds)

def upsert_worksheet(sh, title, rows, cols):
    """Tạo mới worksheet 'title' nếu chưa có, có rồi thì xóa & tạo lại cho sạch."""
    try:
        ws = sh.worksheet(title)
        sh.del_worksheet(ws)
    except gspread.WorksheetNotFound:
        pass
    return sh.add_worksheet(title=title, rows=str(rows), cols=str(cols))

def write_df(ws, df: pd.DataFrame):
    # chuyển NaN -> "" để tránh lỗi khi update
    values = [df.columns.tolist()] + df.astype(object).where(pd.notnull(df), "").values.tolist()
    # gspread update 1 phát cho bảng nhỏ đến vừa; nếu cực lớn thì có thể chunk, nhưng thường không cần
    ws.update(values)

def push_folder_to_sheet(out_dir: Path):
    sheet_key = load_env()
    gc = auth_gspread()
    sh = gc.open_by_key(sheet_key)

    pushed = []
    for fname, tab in TAB_MAP.items():
        csv_path = out_dir / fname
        if not csv_path.exists():
            print(f"[WARN] Skip (missing): {csv_path}")
            continue

        df = pd.read_csv(csv_path)
        # để đủ cột và hàng
        rows = max(2, len(df) + 1)
        cols = max(1, len(df.columns))
        ws = upsert_worksheet(sh, tab, rows, cols)
        write_df(ws, df)
        pushed.append(tab)
        print(f"[OK] Pushed: {tab} ({len(df)} rows)")

    if not pushed:
        print("[INFO] Nothing pushed. Make sure outputs/*.csv exist.")
    else:
        print("[DONE] Updated tabs:", ", ".join(pushed))

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out_dir", type=Path, default=Path("./outputs"), help="Thư mục chứa các CSV đã build")
    args = parser.parse_args()
    push_folder_to_sheet(args.out_dir)

if __name__ == "__main__":
    main()